when:
  - event: push
    branch: "**"

steps:
  - name: sync-time
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    commands:
      - apk add --no-cache ntpdate
      - ntpdate -s pool.ntp.org  # Synchronize with public NTP servers
      - date -u  # Verify corrected time

  - name: build
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    commands:
      - ./gradlew build --scan --info --stacktrace
  - name: format
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    commands:
      - ./gradlew spotlessCheck
  - name: lint
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    commands:
      - ./gradlew pmdMain -Pci