when:
  - event: push
    branch: "**"

steps:
  - name: build
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    environment:
    commands:
      - ./gradlew clean
      - ./gradlew build --scan --info --stacktrace -Djavax.net.ssl.trustStore=/dev/null -Djavax.net.ssl.trustStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=changeit
  - name: format
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    commands:
      - ./gradlew spotlessCheck
  - name: lint
    image: wpilib/roborio-cross-ubuntu:2025-24.04
    commands:
      - ./gradlew pmdMain -Pci